const Robot = require("./models/robot")

const newRobot = new Robot("Mecha Mecha", "Iron", "cleans shoes")

console.log('\n')
console.log('\n')
console.log(newRobot.getName())
console.log(newRobot.getMaterial())
console.log(newRobot.getRole())
console.log('\n')
console.log(newRobot.presentation())
console.log(newRobot.work())
console.log('\n')
console.log(newRobot.upgrade("Gold"))
console.log(newRobot.changeRole("builds houses"))
console.log(newRobot.rename("Megatron"))
console.log('\n')
console.log(newRobot.presentation())
console.log('\n')
console.log('\n')